#!/usr/bin/env bash
# sync-platforms.sh — compile source-of-truth (agents/, skills/, commands/,
# hooks/) into native shape for each supported platform.
#
# Usage:
#   ./scripts/sync-platforms.sh            # all platforms
#   ./scripts/sync-platforms.sh claude-code
#   ./scripts/sync-platforms.sh cursor antigravity codex

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PLATFORMS=("$@")
[[ ${#PLATFORMS[@]} -eq 0 ]] && PLATFORMS=(claude-code cursor antigravity codex)

sync_claude_code() {
  local out="$ROOT/platforms/claude-code/.claude"
  echo "[sync] claude-code -> $out"
  mkdir -p "$out/agents" "$out/skills" "$out/commands" "$out/hooks"

  for f in "$ROOT"/agents/*.md; do
    cp "$f" "$out/agents/$(basename "$f")"
  done

  for f in "$ROOT"/skills/*/*/SKILL.md; do
    local id; id="$(basename "$(dirname "$f")")"
    mkdir -p "$out/skills/$id"
    cp "$f" "$out/skills/$id/SKILL.md"
  done

  for f in "$ROOT"/commands/*.md; do
    cp "$f" "$out/commands/$(basename "$f")"
  done

  for f in "$ROOT"/hooks/*.sh; do
    cp "$f" "$out/hooks/$(basename "$f")"
    chmod +x "$out/hooks/$(basename "$f")"
  done
}

sync_cursor() {
  local out="$ROOT/platforms/cursor/.cursor"
  echo "[sync] cursor -> $out"
  mkdir -p "$out/rules/agents" "$out/rules/skills" "$out/commands" "$out/hooks"

  for f in "$ROOT"/agents/*.md; do
    local id; id="$(basename "$f" .md)"
    {
      echo "---"
      echo "description: \"Agent role: $id\""
      echo "alwaysApply: false"
      echo "globs: [\"**/*\"]"
      echo "---"
      cat "$f"
    } > "$out/rules/agents/$id.mdc"
  done

  for f in "$ROOT"/skills/*/*/SKILL.md; do
    local id; id="$(basename "$(dirname "$f")")"
    {
      echo "---"
      echo "description: \"Skill: $id\""
      echo "alwaysApply: false"
      echo "globs: [\"**/*\"]"
      echo "---"
      cat "$f"
    } > "$out/rules/skills/$id.mdc"
  done

  for f in "$ROOT"/commands/*.md; do
    cp "$f" "$out/commands/$(basename "$f")"
  done

  for f in "$ROOT"/hooks/*.sh; do
    cp "$f" "$out/hooks/$(basename "$f")"
    chmod +x "$out/hooks/$(basename "$f")"
  done
}

sync_antigravity() {
  local out="$ROOT/platforms/antigravity/.antigravity"
  echo "[sync] antigravity -> $out"
  mkdir -p "$out/agents" "$out/skills" "$out/commands" "$out/hooks"

  for f in "$ROOT"/agents/*.md; do
    local id; id="$(basename "$f" .md)"
    cat > "$out/agents/$id.yaml" <<EOF
id: $id
source: ../../agents/$id.md
kind: agent
EOF
  done

  for f in "$ROOT"/skills/*/*/SKILL.md; do
    local id; id="$(basename "$(dirname "$f")")"
    local cat_; cat_="$(basename "$(dirname "$(dirname "$f")")")"
    cat > "$out/skills/$id.yaml" <<EOF
id: $id
category: $cat_
source: ../../skills/$cat_/$id/SKILL.md
kind: skill
EOF
  done

  for f in "$ROOT"/commands/*.md; do
    local id; id="$(basename "$f" .md)"
    cat > "$out/commands/$id.yaml" <<EOF
id: $id
source: ../../commands/$id.md
kind: command
EOF
  done

  for f in "$ROOT"/hooks/*.sh; do
    cp "$f" "$out/hooks/$(basename "$f")"
    chmod +x "$out/hooks/$(basename "$f")"
  done
}

sync_codex() {
  local out="$ROOT/platforms/codex"
  echo "[sync] codex -> $out/AGENTS.md"
  mkdir -p "$out/.codex"

  {
    echo "# AGENTS.md"
    echo
    echo "_Generated by scripts/sync-platforms.sh — do not edit by hand._"
    echo
    echo "This project is governed by an orchestrator-managed agentic"
    echo "development system. The rules below are binding for any agent"
    echo "running through the Codex CLI in this repository."
    echo
    echo "## Lifecycle rules"
    echo
    echo "- Every task MUST be preceded by a written plan committed to"
    echo "  \`logs/plans/<uuid>.json\`."
    echo "- Every coding step MUST be paired with a testing step."
    echo "- Any action with confidence < 0.90 MUST be escalated to the human."
    echo "- Any file matching \`secrets/**\`, \`infra/**\`, \`migrations/**\`,"
    echo "  \`**/.env*\`, \`**/Dockerfile\`, or \`**/*.tf\` is human-gated."
    echo
    echo "## Agents"
    for f in "$ROOT"/agents/*.md; do
      echo
      echo "### Agent: $(basename "$f" .md)"
      echo
      sed -n '/^---$/,/^---$/!p' "$f" | sed 's/^/    /'
    done
    echo
    echo "## Skills"
    for f in "$ROOT"/skills/*/*/SKILL.md; do
      local id; id="$(basename "$(dirname "$f")")"
      echo
      echo "### Skill: $id"
      echo
      sed -n '/^---$/,/^---$/!p' "$f" | sed 's/^/    /'
    done
    echo
    echo "## Commands"
    for f in "$ROOT"/commands/*.md; do
      local id; id="$(basename "$f" .md)"
      echo
      echo "### Command: /$id"
      echo
      sed -n '/^---$/,/^---$/!p' "$f" | sed 's/^/    /'
    done
  } > "$out/AGENTS.md"
}

for p in "${PLATFORMS[@]}"; do
  case "$p" in
    claude-code) sync_claude_code ;;
    cursor) sync_cursor ;;
    antigravity) sync_antigravity ;;
    codex) sync_codex ;;
    *) echo "[sync] unknown platform: $p" >&2; exit 1;;
  esac
done

echo "[sync] done."
