#!/usr/bin/env bash
# session-start-caveman.sh
# Confirms Caveman (https://github.com/juliusbrussee/caveman) is installed
# and exports its env tuning. Does NOT try to inject a `/caveman` slash
# command — Caveman auto-activates inside Claude Code and Codex once the
# binary is on PATH, and uses rule files generated by `caveman --with-init`
# on Cursor / Antigravity.
#
# Exit codes:
#   0  caveman present (or hook intentionally no-op)
#   0  caveman absent — print a hint, fail open (do not block the session)

set -euo pipefail

# Suppress the statusline savings badge by default; harmless if Caveman
# isn't installed.
export CAVEMAN_STATUSLINE_SAVINGS="${CAVEMAN_STATUSLINE_SAVINGS:-0}"

if ! command -v caveman >/dev/null 2>&1; then
  echo "[caveman] not installed — run scripts/install-caveman.sh to enable" >&2
  exit 0
fi

MODE="${ADS_CAVEMAN_MODE:-full}"   # lite|full|ultra|wenyan
echo "[caveman] ready (mode=$MODE, auto-activates on supported hosts)"
